# AUTOGENERATED FROM 'app/queries/create_worker_token.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateWorkerTokenResult(NoPydanticValidation):
    id: uuid.UUID


async def create_worker_token(
    executor: edgedb.AsyncIOExecutor,
    *,
    token: str,
    user_id: uuid.UUID,
) -> CreateWorkerTokenResult:
    return await executor.query_single(
        """\
        insert Token {
            value := <str>$token,
            owner := (
                select Worker
                filter .id = <uuid>$user_id
            )
        }\
        """,
        token=token,
        user_id=user_id,
    )
