# AUTOGENERATED FROM 'app/queries/create_vacancy.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateVacancyResult(NoPydanticValidation):
    id: uuid.UUID


async def create_vacancy(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    about: str,
    skills: list[str],
    company: str,
    salary: float | None,
) -> CreateVacancyResult:
    return await executor.query_single(
        """\
        insert Vacancy {
            name := <str>$name,
            about := <str>$about,
            skills := <array<str>>$skills,
            company := <str>$company,
            salary := <optional float32>$salary
        }\
        """,
        name=name,
        about=about,
        skills=skills,
        company=company,
        salary=salary,
    )
