# AUTOGENERATED FROM 'app/queries/get_employer_by_token.edgeql' WITH:
#     $ python.exe -m edgedb.codegen


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetEmployerByTokenResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    photo: str | None
    birthday: datetime.datetime
    bio: str | None
    hash: str
    email: str
    mentor: list[GetEmployerByTokenResultMentorItem]


@dataclasses.dataclass
class GetEmployerByTokenResultMentorItem(NoPydanticValidation):
    id: uuid.UUID


async def get_employer_by_token(
    executor: edgedb.AsyncIOExecutor,
    *,
    token: str,
) -> GetEmployerByTokenResult | None:
    return await executor.query_single(
        """\
        select Employer {id, name, photo, birthday, bio, hash, email, mentor}
        filter .tokens.value = <str>$token
        limit 1\
        """,
        token=token,
    )
