# AUTOGENERATED FROM 'app/queries/get_worker_by_hash.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetWorkerByHashResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    photo: str


async def get_worker_by_hash(
    executor: edgedb.AsyncIOExecutor,
    *,
    hash: str,
) -> GetWorkerByHashResult | None:
    return await executor.query_single(
        """\
        select Worker {id, name, photo}
        filter Worker.hash = <str>$hash
        limit 1\
        """,
        hash=hash,
    )
