# AUTOGENERATED FROM 'app/queries/get_vacancies.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetVacanciesResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    description: str
    skills: list[str]
    salary: str


async def get_vacancies(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetVacanciesResult]:
    return await executor.query(
        """\
        select Vacancy {
            name,
            description,
            skills,
            salary
        }\
        """,
    )
