# AUTOGENERATED FROM 'app/queries/get_mentors.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetMentorsResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    bio: str | None
    photo: str | None
    skills: list[str]
    salary: float
    resume: str


async def get_mentors(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetMentorsResult]:
    return await executor.query(
        """\
        select Mentor {
            name := .employer.name,
            bio := .employer.bio,
            photo := .employer.photo,
            skills,
            salary,
            resume
        }\
        """,
    )
