# AUTOGENERATED FROM 'app/queries/get_task_blocks_challenges.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetTaskBlocksChallengesResult(NoPydanticValidation):
    id: uuid.UUID
    questions: list[GetTaskBlocksChallengesResultQuestionsItem]
    codes: list[GetTaskBlocksChallengesResultCodesItem]


@dataclasses.dataclass
class GetTaskBlocksChallengesResultCodesItem(NoPydanticValidation):
    id: uuid.UUID
    question: str


@dataclasses.dataclass
class GetTaskBlocksChallengesResultQuestionsItem(NoPydanticValidation):
    id: uuid.UUID
    question: str
    answers: list[str]


async def get_task_blocks_challenges(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetTaskBlocksChallengesResult]:
    return await executor.query(
        """\
        select TaskBlock {
            questions := .questions {
                id,
                question,
                answers
            },
            codes := .codes {
                id,
                question
            }
        }\
        """,
    )
