# AUTOGENERATED FROM 'app/queries/update_worker.edgeql' WITH:
#     $ python.exe -m edgedb.codegen


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateWorkerResult(NoPydanticValidation):
    id: uuid.UUID


async def update_worker(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    bio: str | None,
    photo: str | None,
    resume: str | None,
    skills: list[str] | None,
) -> UpdateWorkerResult | None:
    return await executor.query_single(
        """\
        update Worker
        filter .id = <uuid>$id
        set {
            bio := <optional str>$bio ?? .bio,
            photo := <optional str>$photo ?? .photo,
            resume := <optional str>$resume ?? .resume,
            skills := <optional array<str>>$skills ?? .skills
        }\
        """,
        id=id,
        bio=bio,
        photo=photo,
        resume=resume,
        skills=skills,
    )
