# AUTOGENERATED FROM 'app/queries/update_worker.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import datetime
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateWorkerResult(NoPydanticValidation):
    id: uuid.UUID


async def update_worker(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    birthday: datetime.datetime | None,
    hash: str | None,
    email: str | None,
    bio: str | None,
    photo: str | None,
    resume: str | None,
    skills: list[str] | None,
) -> UpdateWorkerResult | None:
    return await executor.query_single(
        """\
        update Worker
        filter .id = <uuid>$id
        set {
            birthday := <optional datetime>$birthday ?? .birthday,
            hash := <optional str>$hash ?? .hash,
            email := <optional str>$email ?? .email,
            bio := <optional str>$bio ?? .bio,
            photo := <optional str>$photo ?? .photo,
            resume := <optional str>$resume ?? .resume,
            skills := <optional array<str>>$skills ?? .skills
        }\
        """,
        id=id,
        birthday=birthday,
        hash=hash,
        email=email,
        bio=bio,
        photo=photo,
        resume=resume,
        skills=skills,
    )
